//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int Training_Course_Instance_ID { get; set; }
        public int Employee_ID { get; set; }
        public Nullable<bool> Replied_Going { get; set; }
        public Nullable<bool> Actual_Attendance { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual training_course_instance training_course_instance { get; set; }
    }
}
