//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_mailinglist
    {
        public int Client_ID { get; set; }
        public int Mailing_List_ID { get; set; }
        public string Description { get; set; }
    
        public virtual client client { get; set; }
        public virtual mailing_list mailing_list { get; set; }
    }
}
