//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    
    public partial class instructor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public instructor()
        {
            this.training_course_instance = new HashSet<training_course_instance>();
        }


        public int Instructor_ID { get; set; }
        public string Instructor_Name { get; set; }
        public string Instructor_Surname { get; set; }
<<<<<<< HEAD
        public string Instructor_Email { get; set; }
=======

        [Required]
        [EmailAddress]
        [Display(Name = "Instructor Email")]
        public string Instructor_Email { get; set; }

        [Required]
        [Display(Name = "Instructor Cellphone")]
        [Phone]
        public string Instructor_Cellphone { get; set; }

        [Required]
        [Display(Name = "Employee Name")]
>>>>>>> parent of 0eed6af... Validation and TrainingCourseInstanceWorking
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<int> Title_ID { get; set; }
<<<<<<< HEAD
    
        public virtual supplier supplier { get; set; }
=======

        [Required]
        [Display(Name = "Gender")]
        public int Gender_ID { get; set; }

        public virtual employee employee { get; set; }
>>>>>>> parent of 0eed6af... Validation and TrainingCourseInstanceWorking
        public virtual title title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<training_course_instance> training_course_instance { get; set; }
        public virtual employee employee { get; set; }
    }
}
