//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration_token
    {
        public int Registration_Token_ID { get; set; }
<<<<<<< HEAD
=======
        [Display(Name = "Registration Token")]
        [StringLength(40)]
>>>>>>> parent of 0eed6af... Validation and TrainingCourseInstanceWorking
        public string Registration_Token1 { get; set; }
        public string New_Email { get; set; }
<<<<<<< HEAD
=======

        [Display(Name = "Access Level")]
>>>>>>> parent of 0eed6af... Validation and TrainingCourseInstanceWorking
        public Nullable<int> Access_Level_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }

        public virtual access_level access_level { get; set; }
        public virtual employee employee { get; set; }
    }
}
