//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    
    public partial class training_course_instance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public training_course_instance()
        {
            this.attendances = new HashSet<attendance>();
        }
    
        public int Training_Course_Instance_ID { get; set; }
        public Nullable<System.DateTime> Instance_Date { get; set; }
        public Nullable<System.TimeSpan> Instance_Start_Time { get; set; }
        public Nullable<System.TimeSpan> Instance_End_Time { get; set; }
        public Nullable<int> Venue_ID { get; set; }
        public Nullable<int> Instructor_ID { get; set; }
        public Nullable<int> Training_Course_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendance> attendances { get; set; }
        public virtual instructor instructor { get; set; }
        public virtual training_course training_course { get; set; }
        public virtual venue venue { get; set; }
    }
}
