//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROTM
{
    using System;
    using System.Collections.Generic;
    
    public partial class venue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venue()
        {
            this.training_course_instance = new HashSet<training_course_instance>();
        }

        public int Venue_ID { get; set; }
        public string Venue_Name { get; set; }
        public string Venue_Description { get; set; }
<<<<<<< HEAD
=======

        [Required]
        [Display(Name = "Venue Size")]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter valid integer Number")]
>>>>>>> parent of 0eed6af... Validation and TrainingCourseInstanceWorking
        public Nullable<int> Venue_Size { get; set; }
        public Nullable<int> Address_ID { get; set; }

        public virtual address address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<training_course_instance> training_course_instance { get; set; }
    }
}
